defmodule CinderWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :cinder

  # The session is stored in the cookie and signed: readable but not tamperable.
  # signing_salt is derived from secret_key_base at runtime (see config/runtime.exs)
  # so it isn't committed; both the socket (MFA below) and the session plug read it
  # through session_options/0.
  @base_session_options [
    store: :cookie,
    key: "_cinder_key",
    same_site: "Lax"
  ]

  @doc false
  def session_options do
    Keyword.put(
      @base_session_options,
      :signing_salt,
      Application.fetch_env!(:cinder, :session_signing_salt)
    )
  end

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: {__MODULE__, :session_options, []}]],
    longpoll: [connect_info: [session: {__MODULE__, :session_options, []}]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :cinder,
    gzip: not code_reloading?,
    only: CinderWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :cinder
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  # ponytail: re-inits Plug.Session per request so the runtime-derived salt is used
  # (prod inits plugs at compile time). Trivial at household scale; memoize via
  # :persistent_term if it ever shows up in a profile.
  plug :session
  plug CinderWeb.Router

  defp session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(session_options()))
  end
end
